# Generated by Django 3.0.7 on 2020-06-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('total_vendido', models.DecimalField(decimal_places=4, default=0, max_digits=9999)),
                ('nit', models.CharField(max_length=2000, null=True)),
                ('nombre_factura', models.CharField(max_length=2000, null=True)),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'Creado'), (1, 'Pagado'), (2, 'Pago Aceptado'), (-1, 'Pago Rechazado'), (3, 'Entregado'), (-2, 'Anulado')], default=0, protected=True)),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2000)),
                ('descripcion', models.CharField(max_length=2000)),
                ('sku', models.CharField(max_length=2000)),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=9999)),
                ('categoria', models.ManyToManyField(related_name='categorias', to='outime.Categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=4, default=0, max_digits=9999)),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Aprobado'), (-1, 'Anulado')], default=0, protected=True)),
                ('id_venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='outime.Venta')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=9999)),
                ('tipo_movimiento', django_fsm.FSMIntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso')], default=0, protected=True)),
                ('id_producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto_movimiento', to='outime.Producto')),
                ('id_referencia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='referencia', to='outime.Venta')),
            ],
            options={
                'db_table': 'moviento_stock',
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=5000)),
                ('latitud', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitud', models.CharField(blank=True, max_length=10000, null=True)),
                ('id_venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='outime.Venta')),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('precio_venta', models.DecimalField(decimal_places=4, default=0, max_digits=9999)),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='outime.Producto')),
                ('venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='venta_detalle', to='outime.Venta')),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
    ]
