# Generated by Django 3.0.7 on 2020-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
