# Generated by Django 3.0.7 on 2020-07-13 02:17

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('outime', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento_stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto_pagado',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Creado'), (1, 'Pagado'), (2, 'Pago Aceptado'), (-1, 'Pago Rechazado'), (3, 'Entregado'), (-2, 'Anulado'), (-5, 'Iniciado')], default=-5, protected=True),
        ),
    ]
