# Generated by Django 3.0.7 on 2020-07-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outime', '0003_auto_20200712_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='monto_pagado',
            field=models.ImageField(blank=True, null=True, upload_to='comprante_pagos'),
        ),
    ]
